version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "bun"
    groups:
      bun-minor-patch:
        update-types:
          - "minor"
          - "patch"
      bun-major:
        update-types:
          - "major"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "rust"
    groups:
      cargo-minor-patch:
        update-types:
          - "minor"
          - "patch"
      cargo-major:
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
